@baseUrl = http://localhost:8080

### Delete product 1
DELETE {{baseUrl}}/api/v1/products/1

### Delete product 2
DELETE {{baseUrl}}/api/v1/products/2

### Delete product 3
DELETE {{baseUrl}}/api/v1/products/3
